//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class expens
    {
        public int expenseID { get; set; }
        public int expenseAmount { get; set; }
        public string expenseProduct { get; set; }
        public System.DateTime createdOn { get; set; }
    }
}
