//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class simpleAccountsEntities : DbContext
    {
        public simpleAccountsEntities()
            : base("name=simpleAccountsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<purchase> purchases { get; set; }
        public virtual DbSet<sale> sales { get; set; }
        public virtual DbSet<expens> expenses { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<admin> admins { get; set; }
    }
}
